name: "Lint"

on:
  push:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      - name: "Install requirements"
        run: python3 -m pip install -r requirements.txt

      - name: "Run"
        run: python3 -m ruff check --target-version=py313
