name: "Lint"

on:
  push:

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@main

      - name: "Set up Python"
        uses: actions/setup-python@main
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements.txt

      - name: "Run"
        run: python3 -m ruff check --target-version=py311
